# Generated by Django 5.0.1 on 2024-01-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('COM', 'Completed'), ('PAU', 'Paused')], default='ACT', max_length=3),
        ),
    ]
